AI4Bharat/Shoonya-Frontend

src/ui/pages/container/Transliteration/Transliteration.jsx

https://project-sunbird.atlassian.net/browse/SN-44

Automatically enable RTL in transliteration

---

src/ui/pages/component/Tabs/DatasetProjectsTable.jsx

https://project-sunbird.atlassian.net/browse/SN-456

Add export project button in datasets page

---

src/ui/pages/component/Project/TaskTable.jsx

https://project-sunbird.atlassian.net/browse/SN-498

Add user filter for review tasks

---

src/ui/pages/container/Dataset/CreateNewDatasetInstance.jsx

https://project-sunbird.atlassian.net/browse/SN-493

Create dataset button should redirect user to created dataset page

---

src/redux/actions/api/ProjectDetails/GetExportProject.js
src/ui/pages/component/Project/TaskTable.jsx
src/ui/pages/component/Tabs/AdvancedOperation.jsx
src/ui/pages/component/Tabs/DatasetProjectsTable.jsx
src/ui/pages/component/common/DataitemsTable.jsx
src/ui/pages/container/Label-Studio/LSF.jsx
src/ui/pages/container/Label-Studio/lsf.css
src/ui/pages/container/Workspace/AnnotationProject.jsx

https://project-sunbird.atlassian.net/browse/SN-391

Support for Conversation Translation

---

src/ui/pages/container/UserManagement/Login.jsx

https://project-sunbird.atlassian.net/browse/SN-537

Redirect to dashboard if user already logged in

---

src/ui/pages/component/Tabs/BasicSettings.jsx

https://project-sunbird.atlassian.net/browse/SN-451

Add setting for max unlabeled tasks and pull count

---

src/ui/pages/component/Tabs/ReadonlyConfigurations.jsx

View dataset button in project settings under read only.

view dataset button in project settings under read only

---

src/ui/pages/container/Glossary/AddGlossary.jsx

Reverts AI4Bharat/Shoonya-Frontend#415

Revert "Develop"

---

src/ui/pages/container/Glossary/AddGlossary.jsx

Reverts AI4Bharat/Shoonya-Frontend#416

Revert "Revert "Develop""

---

src/redux/actions/api/Dataset/DatasetEditUpdate.js
src/ui/pages/component/Tabs/BasicDatasetSettings.jsx
src/ui/pages/container/Dataset/DatasetDetails.jsx
src/ui/pages/container/Dataset/DatasetSettingTabs.jsx
src/ui/pages/container/Dataset/DatasetSettings.jsx
src/ui/pages/container/Glossary/AddGlossary.jsx
src/web.route.js

added basic settings and advanced settings along with settings_tab_for_dataset

settings_tab_for_dataset

---

src/redux/actions/api/ProjectDetails/DownloadCSVProject.js
src/redux/actions/api/ProjectDetails/DownloadJSONProject.js
src/redux/actions/api/ProjectDetails/DownloadTSVProject.js
src/ui/pages/component/Tabs/AdvancedOperation.jsx
src/ui/pages/container/Project/DownloadProjectButton.jsx

download metadata toggle button added to project download with default state true

download metadata toggle button added to project download

---

src/redux/actions/api/WorkspaceDetails/WorkspaceEditUpdate.js
src/ui/pages/component/Tabs/BasicWorkspaceSettings.jsx
src/ui/pages/component/common/DetailsViewPage.jsx
src/ui/pages/container/Dataset/DatasetDetails.jsx
src/ui/pages/container/Workspace/WorkspaceSettingTabs.jsx
src/web.route.js

Basic and advanced settings added for workspace

basic_and_advanced_settings_for_workspace

---

src/redux/actions/api/ProjectDetails/DownloadCSVProject.js
src/redux/actions/api/ProjectDetails/DownloadJSONProject.js
src/redux/actions/api/ProjectDetails/DownloadTSVProject.js

Passed 'Download matadata' as query param instead of passing it in body data.

Download matadata as query param

---

src/ui/pages/container/UserManagement/ProfileDetails.jsx

code optimized for profiledetails

code optimised removed unwanted code from ProfileDetails.jsx

---

src/ui/pages/component/Project/TaskTable.jsx
src/ui/pages/container/Label-Studio/LSF.jsx
src/ui/pages/container/Label-Studio/ReviewLSF.jsx
src/ui/pages/container/Label-Studio/SuperCheckerLSF.jsx

https://project-sunbird.atlassian.net/browse/SN-769

Fix manager annotation

---

src/ui/pages/container/Label-Studio/LSF.jsx
src/ui/pages/container/Label-Studio/SuperCheckerLSF.jsx

https://project-sunbird.atlassian.net/browse/SN-689

auto save changes

---

src/ui/pages/container/Label-Studio/LSF.jsx
src/ui/pages/container/Label-Studio/SuperCheckerLSF.jsx

Reverts AI4Bharat/Shoonya-Frontend#567

Revert "Revert "auto save changes""

---

src/ui/pages/container/Label-Studio/SuperCheckerLSF.jsx
src/utils/LabelConfig/ConversationTranslation.js

Also hide autosave message for non-supercheckers

Show draggable text area in conversation translation

---

package-lock.json
src/ui/pages/container/CL-Transcription/TranscriptionRightPanel.jsx

Feature SN-833

---

package-lock.json
src/ui/pages/component/CL-Transcription/SettingsButtonComponent.jsx
src/ui/pages/container/CL-Transcription/TranscriptionRightPanel.jsx
src/ui/styles/AudioTranscriptionLandingStyle.js

1. Padding
2. Take speaker b/w time, icons in a single icon for segment.
3. Segment number & Total segments

SN-840 changes 1 to 3

---

src/ui/pages/component/Project/MembersTable.jsx
src/ui/pages/component/Project/SuperCheckerTasks.jsx
src/ui/pages/component/Project/TaskTable.jsx
src/ui/pages/component/Tabs/AdvancedOperation.jsx
src/ui/pages/component/Tabs/Annotators.jsx
src/ui/pages/component/Tabs/ManagersTable.jsx
src/ui/pages/component/Tabs/WorkspaceSetting.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx
src/ui/pages/container/Dataset/DeduplicateDataItems.jsx
src/ui/pages/container/Dataset/DeleteDataItems.jsx
src/ui/pages/container/Project/DeallocationAnnotatorsAndReviewers.jsx
src/ui/pages/container/Project/DeleteProjectTasks.jsx

Changes in - 
1. src/ui/pages/component/project/TaskTable - Deallocate Tasks
2. src/ui/pages/component/project/SuperCheckerTasks - Deallocate Tasks
3. src/ui/pages/component/project/MembersTable - Remove Member, Remove Reviewer
4. src/ui/pages/component/tabs/AdvancedOperations - Archive
5. src/ui/pages/container/project/DeleteProjectTasks - Delete Project Tasks
6. src/ui/pages/container/project/DeallocationAnnotatorsAndReviewers - Deallocate User Tasks
7. src/ui/pages/container/dataset/DeleteDataItems - Delete Data Items
8. src/ui/pages/container/dataset/DeduplicateDataItems - Deduplicate Data Items
9. src/ui/pages/component/tabs/WorkspaceSettings - Archive
10. src/ui/pages/component/tabs/Annotators - Remove Member
11. src/ui/pages/component/tabs/ManagersTable - Remove Manager

password authentication for certain actions

---

src/ui/pages/component/Organization/OrganizationReports.jsx

send mail for org user analysis reports

SN-846: org level user analysis reports

---

src/redux/actions/api/WorkspaceDetails/GetWorkspaceProjectReports.js
src/ui/pages/component/common/WorkspaceReports.jsx

Reverts AI4Bharat/Shoonya-Frontend#811

Revert "Shoonya v2.4"

---

src/redux/actions/api/WorkspaceDetails/GetWorkspaceProjectReports.js
src/ui/pages/component/common/WorkspaceReports.jsx

Reverts AI4Bharat/Shoonya-Frontend#812

Revert "Revert "Shoonya v2.4""

---

src/redux/actions/api/WorkspaceDetails/GetWorkspaceProjectReports.js
src/ui/pages/component/common/WorkspaceReports.jsx

Reverts AI4Bharat/Shoonya-Frontend#814

Revert "Revert "Revert "Shoonya v2.4"""

---

src/ui/pages/component/Organization/OrganizationReports.jsx
src/ui/pages/component/common/WorkspaceReports.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx
src/ui/pages/container/UserManagement/ScheduleMails.jsx

dependant https://github.com/AI4Bharat/Shoonya-Backend/pull/863

autosave refactor + ocr stats

---

package-lock.json
package.json
src/ui/pages/container/Admin/AnnotationDetails.jsx
src/ui/pages/container/Admin/DashBoard.jsx
src/ui/pages/container/Admin/TaskDetails.jsx
src/ui/pages/container/Progress/TaskAnalytics/ContextualTranslationEditing.jsx

https://project-sunbird.atlassian.net/browse/SN-859

SN-859 'Task Details' and 'Annotation Details' tabs in 'Admin' page

---

src/ui/pages/component/CL-Transcription/AnnotationStageButtons.jsx

Bug-fix for disabling 'Update' button for an annotation displayed in read-only mode

Shoonya v2.4 patch 

---

src/ui/pages/container/CL-Transcription/AllAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx

Minor fix to refresh Wavesurfer UI after every button click.

Shoonya v2.6.2 Patch

---

src/ui/pages/container/Label-Studio/AllTaskLSF.jsx
src/ui/pages/container/Label-Studio/LSF.jsx
src/ui/pages/container/Label-Studio/ReviewLSF.jsx
src/ui/pages/container/Label-Studio/SuperCheckerLSF.jsx
src/ui/pages/container/Label-Studio/labelConfigJSX.js

Please review the changes and let me know

updated the labeling of files and added labels

---

src/config/dropDownValues.js

Added a new dropdown contract basis in edit profile page

SN-800 "Contract basis addition in admin page"

---

src/redux/actions/api/ProjectDetails/DeallocationAnnotatorsAndReviewers.js
src/redux/actions/api/Tasks/DeAllocateSuperCheckerTasks.js
src/redux/actions/api/Tasks/DeallocateReviewTasks.js
src/redux/actions/api/Tasks/DeallocateTasks.js
src/ui/pages/component/Project/TaskTable.jsx
src/ui/pages/container/Project/DeallocationAnnotatorsAndReviewers.jsx

Hey Updated the changes for the reviewer by task ID

Updataed deallocation 

---

src/ui/pages/container/Admin/TaskDetails.jsx

Added a project page button in admin tab

Added a project page button in admin tab

---

src/redux/actions/api/Organization/ApproveManagerSuggestions.js
src/ui/pages/component/common/DetailsViewPage.jsx

minor fix in decentralized approvals

---

src/ui/pages/component/Project/MembersTable.jsx
src/ui/pages/component/Tabs/Invites.jsx
src/ui/pages/component/common/DetailsViewPage.jsx
src/ui/pages/component/common/InviteUsersDialog.jsx

Added page refresh by calling the pending users invite endpoint and custom dialog/pop-up for the different users based on roles.

popup customization and page refresh after clicking action buttons 

---

src/ui/pages/container/CL-Transcription/AllAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/AudioPanel.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/wavesurfer.jsx

Reverts AI4Bharat/Shoonya-Frontend#1016

Revert "changed audio urls for ANTE type"

---

src/ui/Layout.js
src/ui/pages/container/CL-Transcription/AllAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/AnnotationTranscription.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/StandardisedTranscription.jsx
src/web.route.js

Updated the minor fix from frontend

Frontend-fix-SDTE-minor fix

---

src/ui/pages/component/common/InviteUsersDialog.jsx

Invite user dialog styles changed

Invite Users Dialog

---

src/ui/pages/container/Project/DeallocationAnnotatorsAndReviewers.jsx

Removed a few options from the de-allocation drop downs

De-allocation drop down options - changed

---

src/redux/actions/CL-Transcription/SaveTranscript.js
src/ui/pages/component/CL-Transcription/SettingsButtonComponent.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/StandardizedTranscription.jsx
src/ui/pages/container/Workspace/AnnotationProject.jsx

Minor updates for acoustic enabled stage and standardised transcription editing type project

Final-updates for new project creation STDE

---

src/redux/actions/CL-Transcription/SaveTranscript.js
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx

Made changes for displaying the Tabs for L3

Update the L3 tab using the accoustic-enable-stage 

---

src/ui/pages/container/Label-Studio/LSF.jsx
src/ui/pages/container/Label-Studio/ReviewLSF.jsx
src/ui/pages/container/Label-Studio/SuperCheckerLSF.jsx
src/ui/pages/container/Transliteration/RomanisedTransliteration.jsx

Added feature to expand or minimize the textbox

Contextual transliteration contact source fix

---

src/ui/pages/container/CL-Transcription/AllAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx

Reverts AI4Bharat/Shoonya-Frontend#1067

Revert "add loader until audio is loaded"

---

src/ui/pages/container/CL-Transcription/AllAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/AudioPanel.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/wavesurfer.jsx

Reverts AI4Bharat/Shoonya-Frontend#1059

Revert "use shoonya-backend for audio data"

---

src/ui/pages/container/CL-Transcription/AllAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/AudioPanel.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/wavesurfer.jsx

Reverts AI4Bharat/Shoonya-Frontend#1069

Revert "Revert "use shoonya-backend for audio data""

---

src/ui/pages/container/CL-Transcription/AllAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx

Reverts AI4Bharat/Shoonya-Frontend#1068

Revert "Revert "add loader until audio is loaded""

---

src/ui/pages/component/common/Header.jsx
src/ui/pages/container/Progress/MetaAnalytics/MetaAnalytics.jsx
src/ui/pages/container/Progress/TaskAnalytics/TaskAnalytics.jsx

Reverts AI4Bharat/Shoonya-Frontend#1097

Revert "analytics api integration effciency and download button ui changes"

---

src/redux/reducers/Progress/TaskAnalytics.js
src/redux/reducers/WorkspaceDetails/GetTaskAnalytics.js
src/ui/pages/container/Progress/MetaAnalytics/MetaAnalytics.jsx
src/ui/pages/container/Progress/MetaAnalytics/SentanceCountMetaAnalyticsChart.jsx
src/ui/pages/container/Progress/MetaAnalytics/WordCountMetaAnalyticsChart.jsx
src/ui/pages/container/Progress/TaskAnalytics/AudioTaskAnalyticsChart.jsx
src/ui/pages/container/Progress/TaskAnalytics/TaskAnalytics.jsx
src/ui/pages/container/Progress/TaskAnalytics/TaskCountAnalyticsChart.jsx
src/ui/pages/container/Progress/Workspace/MetaAnalytics.jsx
src/ui/pages/container/Progress/Workspace/TaskAnalytics.jsx
src/ui/styles/Dataset.js

Reverts AI4Bharat/Shoonya-Frontend#1110

Revert "task analytics for superchecker"

---

src/redux/reducers/Progress/TaskAnalytics.js
src/redux/reducers/WorkspaceDetails/GetTaskAnalytics.js
src/ui/pages/container/Progress/MetaAnalytics/MetaAnalytics.jsx
src/ui/pages/container/Progress/MetaAnalytics/SentanceCountMetaAnalyticsChart.jsx
src/ui/pages/container/Progress/MetaAnalytics/WordCountMetaAnalyticsChart.jsx
src/ui/pages/container/Progress/TaskAnalytics/AudioTaskAnalyticsChart.jsx
src/ui/pages/container/Progress/TaskAnalytics/TaskAnalytics.jsx
src/ui/pages/container/Progress/TaskAnalytics/TaskCountAnalyticsChart.jsx
src/ui/pages/container/Progress/Workspace/MetaAnalytics.jsx
src/ui/pages/container/Progress/Workspace/TaskAnalytics.jsx
src/ui/styles/Dataset.js

Reverts AI4Bharat/Shoonya-Frontend#1111

Revert "Revert "task analytics for superchecker""

---

src/ui/pages/container/CL-Transcription/TranscriptionRightPanel.jsx

Reverts AI4Bharat/Shoonya-Frontend#1141

Revert "Analytic org UI"

---

src/ui/pages/container/CL-Transcription/AllAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx

Reverts AI4Bharat/Shoonya-Frontend#1070

Revert "use asr server instead of shoonya-backend for getting audio blob"

---

src/ui/pages/component/common/Header.jsx
src/ui/pages/container/UserManagement/AppInfo.jsx
src/ui/pages/container/UserManagement/Login.jsx
src/ui/styles/header.js
src/ui/styles/loginStyle.js

- made shoonya's header responsive
- fixed login responsiveness which was breaking b/w 700px to 900px

Header responsive

---

src/ui/pages/component/common/Spinner.jsx
src/ui/styles/Dataset.js

Fix spinner alignment to ensure it is centered properly.

Fix spinner alignment to ensure it is centered properly.

---

src/ui/pages/component/Tabs/AdvancedOperation.jsx
src/ui/pages/component/Tabs/BasicDatasetSettings.jsx
src/ui/pages/component/Tabs/BasicSettings.jsx
src/ui/pages/component/Tabs/ReadonlyConfigurations.jsx
src/ui/pages/container/Dataset/DatasetSettingTabs.jsx
src/ui/pages/container/Dataset/DatasetSettings.jsx
src/ui/pages/container/Dataset/DeduplicateDataItems.jsx
src/ui/pages/container/Dataset/DeleteDataItems.jsx
src/ui/pages/container/Dataset/DownloadDataSetButton.jsx
src/ui/pages/container/Project/DeallocationAnnotatorsAndReviewers.jsx
src/ui/pages/container/Project/DeleteProjectTasks.jsx
src/ui/pages/container/Project/DownloadProjectButton.jsx
src/ui/pages/container/Project/ProjectLogs.jsx
src/ui/pages/container/Project/ProjectSetting.jsx
src/ui/pages/container/Project/SuperCheckSettings.jsx

This PR improves the responsiveness of the Project Settings and Datasets Settings page.
Adjustments include:
- Fixing layout issues on smaller screens
- Ensuring proper alignment of form fields and buttons
- Improving spacing and scaling for a better user experience
- Resolving any overflow or text-wrapping problems

Project settings datasets settings page responsive

---

src/ui/pages/container/CL-Transcription/AllAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/TranscriptionRightPanel.jsx

Reverts AI4Bharat/Shoonya-Frontend#1179

Revert "arrow"

---

src/ui/pages/component/Organization/OrganizationReports.jsx
src/ui/pages/component/Project/AllTaskTable.jsx
src/ui/pages/component/Project/MembersTable.jsx
src/ui/pages/component/Project/ProjectAnalytics.jsx
src/ui/pages/component/Project/ReportsTable.jsx
src/ui/pages/component/Project/SuperChecker.jsx
src/ui/pages/component/Project/SuperCheckerTasks.jsx
src/ui/pages/component/Project/TaskTable.jsx
src/ui/pages/component/Tabs/Annotators.jsx
src/ui/pages/component/Tabs/AnnotatorsTable.jsx
src/ui/pages/component/Tabs/DatasetProjectsTable.jsx
src/ui/pages/component/Tabs/ManagersTable.jsx
src/ui/pages/component/Tabs/MyProgress.jsx
src/ui/pages/component/Tabs/ProjectTable.jsx
src/ui/pages/component/Tabs/RecentTasks.jsx
src/ui/pages/component/common/DataitemsTable.jsx
src/ui/pages/component/common/DatasetReports.jsx
src/ui/pages/component/common/Header.jsx
src/ui/pages/component/common/MobileNavbar.jsx
src/ui/pages/component/common/WorkspaceReports.jsx
src/ui/pages/component/common/WorkspaceTable.jsx
src/ui/pages/container/Admin/QueuedTasksDetails.jsx
src/ui/pages/container/Admin/UserDetail.jsx
src/ui/pages/container/Dataset/DatasetCardList.jsx
src/ui/pages/container/Dataset/DatasetLogs.jsx
src/ui/pages/container/Glossary/Glossary.jsx
src/ui/pages/container/Project/ProjectCardList.jsx
src/ui/pages/container/Project/ProjectLogs.jsx
src/ui/pages/container/UserManagement/ScheduleMails.jsx
src/ui/pages/container/Workspace/AnnotationProject.jsx

Reverts AI4Bharat/Shoonya-Frontend#1176

Revert "Tia dev"

---

src/ui/pages/component/CL-Transcription/SettingsButtonComponent.jsx
src/ui/pages/container/CL-Transcription/AllAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/TranscriptionRightPanel.jsx

Reverts AI4Bharat/Shoonya-Frontend#1236

Revert "Fix doublehash tlp shortcut"

---

src/ui/pages/container/Label-Studio/LSF.jsx

Fixed the overlapping of data on the LSF page

Fix overlap lsf

---

src/ui/pages/component/CL-Transcription/SettingsButtonComponent.jsx
src/ui/pages/container/CL-Transcription/AllAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/TranscriptionRightPanel.jsx

Reverts AI4Bharat/Shoonya-Frontend#1241

Revert "Fix doublehash and tlp shortcuts"

---

src/ui/pages/component/CL-Transcription/SettingsButtonComponent.jsx
src/ui/pages/container/CL-Transcription/AllAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/ReviewAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/SuperCheckerAudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/TranscriptionRightPanel.jsx

Reverts AI4Bharat/Shoonya-Frontend#1242

Revert "Revert "Fix doublehash and tlp shortcuts""

---

src/ui/pages/component/CL-Transcription/AnnotationStageButtons.jsx
src/ui/pages/component/CL-Transcription/SettingsButtonComponent.jsx
src/ui/pages/container/CL-Transcription/AudioPanel.jsx
src/ui/pages/container/CL-Transcription/AudioTranscriptionLandingPage.jsx
src/ui/pages/container/CL-Transcription/TimeBoxes.jsx
src/ui/pages/container/CL-Transcription/TranscriptionRightPanel.jsx
src/ui/styles/AudioTranscriptionLandingStyle.js
src/ui/styles/LayoutStyles.js

Made atlp responsive for all screen sizes

make atlp responsive for all screen sizes
